title: HomeOS
description: More than a theme for Home Assistant
theme: just-the-docs

url: https://HomeOS.github.io

aux_links:
  Template Repository: https://github.com/avenger11/HomeOS
  
color_scheme: dark
