title: HomeOS
description: More than a theme for Home Assistant
theme: just-the-docs

url: https://HomeOS.github.io

aux_links:
  HomeOS Repository: 
  -  "https://github.com/avenger11/HomeOS"

aux_links_new_tab: true
  
color_scheme: dark
